name: Sauce Cypress Pipeline Demo Tests

on:
  pull_request:
  push:
    branches:
      - master

env:
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCECTL_VERSION: 0.34.1

jobs:
  cypress-job:
    runs-on: ubuntu-latest # which OS
    steps:
      - name: Checkout Github Code # taking all code where this file exists
        uses: actions/checkout@v2 # pulling from code here: https://github.com/actions/checkout
      - name: Download saucectl
        run: |
          SAUCECTL_BINARY=saucectl_${SAUCECTL_VERSION}_linux_64-bit.tar.gz
          curl -L -o ${SAUCECTL_BINARY} \
              -H "Accept: application/octet-stream" \
              https://github.com/saucelabs/saucectl/releases/download/v${SAUCECTL_VERSION}/${SAUCECTL_BINARY} \
              && tar -xvzf ${SAUCECTL_BINARY}
      - name: Workaround for container permissions
        run: sudo chmod -R 777 cypress/ #updated
      - name: Run Saucy Tests
        run: |
          ./saucectl run
        env:
          BUILD_ID: ${{ github.run_id }}
          BUILD_ENV: GitHub Actions
